config/routes.rb
Rails.application.routes.draw do

  resources :github_accounts do
    resources :repos do
      
    end
  end

  root :to => 'root#index'

  resources :branches do
    member do
      post :run_tests
    end
    resources :test_runs do
      resources :examples
    end
  end  

  get 'auth/github' => 'third_party_authentication#github'

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  has_many :branches
  belongs_to :github_account
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :set_repo, only: [:show, :edit, :update, :destroy]
  before_action :set_github_account

  # GET /repos
  # GET /repos.json
  def index
    @repos = collection
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
    @github_account = GithubAccount.find(params[:github_account_id])
    @branches = @github_account.client.branches(@repo.github_name).map(&:to_h)
    @existing = @repo.branches.select(:name, :id)
    @branches.each do |branch|
      match = @existing.find{ |b| b.name.to_s == branch[:name].to_s }
      if !match.nil?
        branch[:tracked] = true
        branch[:ci_url] = branch_path(match)
      end
    end
  end

  # GET /repos/new
  def new
    @repo = collection.new    
    get_possible_repo_names
  end

  # GET /repos/1/edit
  def edit
    get_possible_repo_names
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = collection.create(repo_params)

    respond_to do |format|
      if @repo.errors.empty?
        format.html { redirect_show @repo, notice: 'Repo was successfully created.' }
        format.json { render :show, status: :created, location: @repo }
      else
        format.html { render :new }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1
  # PATCH/PUT /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_show @repo, notice: 'Repo was successfully updated.' }
        format.json { render :show, status: :ok, location: @repo }
      else
        format.html { render :edit }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo.destroy
    respond_to do |format|
      format.html { redirect_index notice: 'Repo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def get_possible_repo_names
      @github_account = GithubAccount.find(params[:github_account_id])
      keys = [:full_name]
      @possible_repos = @github_account.client.repos.map{ |r| r.to_h.select{ |k, v| keys.include?(k) } }
    end

    def set_github_account
      @github_account = GithubAccount.new(:id => params[:github_account_id])
    end

    def redirect_index(*args)
      redirect_to(github_account_repos_url(:github_account_id => params[:github_account_id]), *args)
    end

    def redirect_show(repo, *args)
      redirect_to(github_account_repo_url(:id => repo.id, :github_account_id => repo.github_account_id), *args)
    end

    def collection      
      Repo.where(:github_account_id => params[:github_account_id])
    end

    def set_repo
      @repo = collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repo_params
      params.require(:repo).permit(:name, :github_name, :last_synced)
    end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_form.html.erb
<%= form_for([@github_account, @repo]) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :github_name %><br>
    <%= f.select :github_name, options_for_select(@possible_repos.map{|r| r[:full_name]}) %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repos/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', github_account_repo_path %> |
<%= link_to 'Back', github_account_repos_path %>

app/views/repos/index.html.erb
<h1>Listing repos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Github account</th>
      <th>Github name</th>
      <th>Last synced</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repos.each do |repo| %>
      <tr>
        <td><%= repo.name %></td>
        <td><%= repo.github_account_id %></td>
        <td><%= repo.github_name %></td>
        <td><%= repo.last_synced %></td>
        <td><%= link_to 'Show', github_account_repo_path(:id => repo.id, :github_account_id => repo.github_account_id) %></td>
        <td><%= link_to 'Edit', edit_github_account_repo_path(:id => repo.id, :github_account_id => repo.github_account_id) %></td>
        <td><%= link_to 'Destroy', github_account_repo_path(:id => repo.id, :github_account_id => repo.github_account_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repo', new_github_account_repo_path %>

app/views/repos/new.html.erb
<h1>New repo</h1>

<%= render 'form' %>

<%= link_to 'Back', github_account_repos_path %>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repo.name %>
</p>

<p>
  <strong>Github account:</strong>
  <%= @repo.github_account_id %>
</p>

<p>
  <strong>Github name:</strong>
  <%= @repo.github_name %>
</p>

<p>
  <strong>Last synced:</strong>
  <%= @repo.last_synced %>
</p>

<table>
  <tr>
    <th>Name</th><th>Tracked</th><th>Actions</th>
  </tr>
  <% @branches.each do |branch| %>
    <tr>
      <td><%= branch[:name] %></td>
      <td><%= branch[:tracked] || 'false' %></td>
      <td>
        <% if branch[:tracked] %>
          <a href="<%= branch[:ci_url] %>">view</a>
          <a href="<%= branch[:ci_url] %>" data-method="delete">stop tracking</a>
        <% else %>
          <form style="display:none" action="<%= branches_url %>" method="post">
            <%= token_tag %>
            <input type="hidden" name="branch[name]" value="<%= branch[:name] %>"></input>
            <input type="hidden" name="branch[repo_id]" value="<%= @repo.id %>"></input>
          </form>
          <a href="<%= branches_url %>/<%= branch[:name] %>" class="create_branch_link">track</a>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_github_account_repo_path %> |
<%= link_to 'Back', github_account_repos_path %>