config/routes.rb
Rails.application.routes.draw do

  resources :github_accounts do
    resources :repos do
      
    end
  end

  root :to => 'root#index'

  resources :branches do
    member do
      post :run_tests
    end
    resources :test_runs do
      resources :examples
    end
  end  

  get 'auth/github' => 'third_party_authentication#github'

end

app/models/github_account.rb
class GithubAccount < ActiveRecord::Base
  def client
    Octokit::Client.new(:access_token => self.access_token || '')
  end

  def authorized?
    begin 
      client.user
    rescue Octokit::Unauthorized => e
      return false
    end
    true
  end

end

app/controllers/github_accounts_controller.rb
class GithubAccountsController < ApplicationController
  before_action :set_github_account, only: [:show, :edit, :update, :destroy]

  # GET /github_accounts
  # GET /github_accounts.json
  def index
    @github_accounts = GithubAccount.all
  end

  # GET /github_accounts/1
  # GET /github_accounts/1.json
  def show
    @state = SecureRandom.urlsafe_base64(16)
    session[@state] = @github_account.id
  end

  # GET /github_accounts/new
  def new
    @github_account = GithubAccount.new
  end

  # GET /github_accounts/1/edit
  def edit
  end

  # POST /github_accounts
  # POST /github_accounts.json
  def create
    @github_account = GithubAccount.new(github_account_params)

    respond_to do |format|
      if @github_account.save
        format.html { redirect_to @github_account, notice: 'Github account was successfully created.' }
        format.json { render :show, status: :created, location: @github_account }
      else
        format.html { render :new }
        format.json { render json: @github_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /github_accounts/1
  # PATCH/PUT /github_accounts/1.json
  def update
    respond_to do |format|
      if @github_account.update(github_account_params)
        format.html { redirect_to @github_account, notice: 'Github account was successfully updated.' }
        format.json { render :show, status: :ok, location: @github_account }
      else
        format.html { render :edit }
        format.json { render json: @github_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /github_accounts/1
  # DELETE /github_accounts/1.json
  def destroy
    @github_account.destroy
    respond_to do |format|
      format.html { redirect_to github_accounts_url, notice: 'Github account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_github_account
      @github_account = GithubAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def github_account_params
      params.require(:github_account).permit(:name, :client_id, :client_secret, :url)
    end
end

app/helpers/github_accounts_helper.rb
module GithubAccountsHelper
end

app/views/github_accounts/_form.html.erb
<%= form_for(@github_account) do |f| %>
  <% if @github_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@github_account.errors.count, "error") %> prohibited this github_account from being saved:</h2>

      <ul>
      <% @github_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :client_secret %><br>
    <%= f.text_field :client_secret %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/github_accounts/edit.html.erb
<h1>Editing github_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @github_account %> |
<%= link_to 'Back', github_accounts_path %>

app/views/github_accounts/index.html.erb
<h1>Listing github_accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Client ID</th>      
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @github_accounts.each do |github_account| %>
      <tr>
        <td><%= github_account.name %></td>
        <td><%= github_account.client_id %></td>
        <td><%= github_account.client_secret %></td>
        <td><%= github_account.username %></td>
        <td><%= link_to 'Show', github_account %></td>
        <td><%= link_to 'Edit', edit_github_account_path(github_account) %></td>
        <td><%= link_to 'Destroy', github_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Github account', new_github_account_path %>

app/views/github_accounts/new.html.erb
<h1>New github_account</h1>

<%= render 'form' %>

<%= link_to 'Back', github_accounts_path %>

app/views/github_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @github_account.name %>
</p>

<p>
  <strong>Client:</strong>
  <%= @github_account.client_id %>
</p>

<p>
  <strong>Username:</strong>
  <%= @github_account.username %>
</p>

<% if !@github_account.authorized? %>

<%
  redirect = u(request.protocol + request.host_with_port + '/auth/github')
url = "https://github.com/login/oauth/authorize?client_id=#{@github_account.client_id}&redirect_uri=#{redirect}&scope=repo&state=#{@state}" %>

<% end %>

<a href="<%= url %>">Authorize</a>

<%= link_to 'Edit', edit_github_account_path(@github_account) %> |
<%= link_to 'Back', github_accounts_path %>
<%= link_to 'Repos', github_account_repos_path(:github_account_id => @github_account.id) %>