config/routes.rb
Rails.application.routes.draw do

  resources :github_accounts do
    resources :repos do
      
    end
  end

  root :to => 'root#index'

  resources :branches do
    member do
      post :run_tests
    end
    resources :test_runs do
      resources :examples
    end
  end  

  get 'auth/github' => 'third_party_authentication#github'

end

app/models/test_run.rb
class TestRun < ActiveRecord::Base
  has_many :examples
end

app/controllers/test_runs_controller.rb
class TestRunsController < ApplicationController
  before_action :set_test_run, only: [:show, :edit, :update, :destroy]

  # GET /test_runs
  # GET /test_runs.json
  def index
    @test_runs = TestRun.all
  end

  # GET /test_runs/1
  # GET /test_runs/1.json
  def show
  end

  # GET /test_runs/new
  def new
    @test_run = TestRun.new
  end

  # GET /test_runs/1/edit
  def edit
  end

  # POST /test_runs
  # POST /test_runs.json
  def create
    @test_run = TestRun.new(test_run_params)

    respond_to do |format|
      if @test_run.save
        format.html { redirect_to @test_run, notice: 'Test run was successfully created.' }
        format.json { render :show, status: :created, location: @test_run }
      else
        format.html { render :new }
        format.json { render json: @test_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_runs/1
  # PATCH/PUT /test_runs/1.json
  def update
    respond_to do |format|
      if @test_run.update(test_run_params)
        format.html { redirect_to @test_run, notice: 'Test run was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_run }
      else
        format.html { render :edit }
        format.json { render json: @test_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_runs/1
  # DELETE /test_runs/1.json
  def destroy
    @test_run.destroy
    respond_to do |format|
      format.html { redirect_to test_runs_url, notice: 'Test run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_run
      @test_run = TestRun.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_run_params
      params.require(:test_run).permit(:branch_id, :status)
    end
end

app/helpers/test_runs_helper.rb
module TestRunsHelper
end

app/views/test_runs/_form.html.erb
<%= form_for(@test_run) do |f| %>
  <% if @test_run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_run.errors.count, "error") %> prohibited this test_run from being saved:</h2>

      <ul>
      <% @test_run.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :branch_id %><br>
    <%= f.number_field :branch_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_runs/edit.html.erb
<h1>Editing test_run</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_run %> |
<%= link_to 'Back', test_runs_path %>

app/views/test_runs/index.html.erb
<h1>Listing test_runs</h1>

<table>
  <thead>
    <tr>
      <th>Branch</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_runs.each do |test_run| %>
      <tr>
        <td><%= test_run.branch_id %></td>
        <td><%= test_run.status %></td>
        <td><%= link_to 'Show', test_run %></td>
        <td><%= link_to 'Edit', edit_test_run_path(test_run) %></td>
        <td><%= link_to 'Destroy', test_run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test run', new_test_run_path %>

app/views/test_runs/new.html.erb
<h1>New test_run</h1>

<%= render 'form' %>

<%= link_to 'Back', test_runs_path %>

app/views/test_runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Branch:</strong>
  <%= @test_run.branch_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @test_run.status %>
</p>

<%= link_to 'Edit', edit_test_run_path(@test_run) %> |
<%= link_to 'Back', test_runs_path %>